---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 14104.
--- DateTime: 2026/3/13 11:04
---

local M = {}

local PrintString = UE.UKismetSystemLibrary.PrintString

function M.Print(text, color, duration)
    -- or后边指没有参数传入时的默认值
    color = color or UE.FLinearColor(1, 1, 1, 1)
    duration = duration or 100
    PrintString(nil, text, true, false, color, duration)
end

return M